repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version or the one you need
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Again, use the latest version
    hooks:
      - id: black
        language_version: python3.10  # Specify the Python version you're using
