repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version
    hooks:
      - id: isort
  
  - repo: https://github.com/psf/black
    rev: 24.8.0  # Use the latest version
    hooks:
      - id: black
